services:
  mineru:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8786:7860"
      - "31000:30000"
    volumes:
      - ./data:/mineru/data
    environment:
      - MINERU_DEVICE_MODE=cpu
      - MINERU_MODEL_SOURCE=local
      - MINERU_FORMULA_ENABLE=true
      - MINERU_TABLE_ENABLE=true
    restart: unless-stopped
    shm_size: 32g
